version: '3'
services:
  app:
    container_name: app
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
